### ISSUE TITLE
Study for final

### ISSUE THREAD

**Issue by arosenbe** [arosenbe/econ-270#9]

**Comment by arosenbe** [comment]
@stanfordquan we can track our study progress here.

## 2013
  1.  Done

**Comment by stanfordquan** [comment]
fyi a complete solution of the N(0,\sigma) Neyman Pearson example is in the orange folder

**Comment by stanfordquan** [comment]
-  Amemiya
 - example 9.3.2

**Comment by stanfordquan** [comment]
great progress

**Comment by arosenbe** [comment]
Done!
